from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path

import pytest

from grace.pipeline.orchestrate import PipelineHooks, run_pipeline
from grace.pipeline.types import GenerationContext, GenerationResult, PspDocs


@dataclass
class _StubRunner:
    files_to_create: list[tuple[str, str]]

    async def is_available(self) -> tuple[bool, str]:
        return (True, "ok")

    async def generate(self, ctx: GenerationContext) -> GenerationResult:
        written: list[Path] = []
        for name, body in self.files_to_create:
            p = ctx.output_dir / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)
            written.append(p)
        return GenerationResult(
            output_dir=ctx.output_dir,
            files_written=written,
            stdout="",
            stderr="",
            exit_code=0,
        )


@pytest.fixture
def stub_ctx(tmp_path: Path) -> GenerationContext:
    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    return GenerationContext(
        psp_name="cashfree",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "out",
        target_module="lens.connectors.cashfree",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="2024-09-01",
    )


def test_run_pipeline_post_processes_marker(stub_ctx: GenerationContext) -> None:
    runner = _StubRunner(files_to_create=[("connector.py", "x = 1\n")])
    asyncio.run(run_pipeline(ctx=stub_ctx, runner=runner, hooks=PipelineHooks(run_gates=False)))
    out = (stub_ctx.output_dir / "connector.py").read_text()
    assert out.startswith("# ─")
    assert "x = 1" in out


def test_run_pipeline_skips_existing_marker(stub_ctx: GenerationContext) -> None:
    marker = (
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree 2024-09-01\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
    )
    runner = _StubRunner(files_to_create=[("connector.py", marker + "\nx = 1\n")])
    asyncio.run(run_pipeline(ctx=stub_ctx, runner=runner, hooks=PipelineHooks(run_gates=False)))
    out = (stub_ctx.output_dir / "connector.py").read_text()
    assert out.count("DO NOT EDIT — autogenerated by Grace.") == 1
