from __future__ import annotations

from pathlib import Path

from grace.pipeline.marker import ensure_marker, has_marker, render_marker


def test_render_marker_seven_lines() -> None:
    text = render_marker(
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="https://docs.cashfree.com/openapi.yaml",
    )
    lines = text.strip("\n").splitlines()
    assert len(lines) == 7
    assert lines[1] == "#  DO NOT EDIT — autogenerated by Grace."


def test_has_marker_recognizes_well_formed(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree v1\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
        "\n"
        "x = 1\n"
    )
    assert has_marker(p) is True


def test_has_marker_rejects_missing(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    assert has_marker(p) is False


def test_ensure_marker_prepends_when_absent(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    text = p.read_text()
    assert text.startswith("# ─")
    assert "x = 1" in text


def test_ensure_marker_idempotent(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    once = p.read_text()
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    twice = p.read_text()
    assert once == twice


def test_ensure_marker_normalizes_stamp_when_present(tmp_path: Path) -> None:
    """A marker already authored by the generation backend with a wrong
    timestamp/version has its Grace-authoritative fields (Generated, Generator)
    overwritten, while the descriptive Source/Regenerate lines are preserved."""
    p = tmp_path / "x.py"
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree connector_docs/cashfree\n"
        "#  Generated: 2026-06-03T00:00:00Z\n"
        "#  Generator: grace 0.0.1\n"
        "#  Regenerate: grace generate cashfree --domain subscriptions --from connector_docs/cashfree\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
        "\n"
        "x = 1\n"
    )
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-06-03T09:54:25Z",
        grace_version="0.9.0",
        source_uri="x",
    )
    text = p.read_text()
    # Grace-authoritative fields overwritten:
    assert "#  Generated: 2026-06-03T09:54:25Z\n" in text
    assert "#  Generator: grace 0.9.0\n" in text
    assert "2026-06-03T00:00:00Z" not in text  # stale timestamp gone
    assert "grace 0.0.1" not in text  # stale version gone
    # descriptive fields preserved (backend's --domain Regenerate kept):
    assert "#  Source: cashfree connector_docs/cashfree\n" in text
    assert "--domain subscriptions" in text
    # not duplicated, code intact:
    assert text.count("DO NOT EDIT — autogenerated by Grace.") == 1
    assert text.rstrip().endswith("x = 1")
