from __future__ import annotations

import asyncio
from dataclasses import dataclass, replace
from pathlib import Path

import pytest

from grace.pipeline.orchestrate import (
    PipelineHooks,
    _relocate_tests,
    relocated_tests_path,
    run_pipeline,
)
from grace.pipeline.types import GenerationContext, GenerationResult, PspDocs


@dataclass
class _StubRunner:
    files_to_create: list[tuple[str, str]]

    async def is_available(self) -> tuple[bool, str]:
        return (True, "ok")

    async def generate(self, ctx: GenerationContext) -> GenerationResult:
        written: list[Path] = []
        for name, body in self.files_to_create:
            p = ctx.output_dir / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)
            written.append(p)
        return GenerationResult(
            output_dir=ctx.output_dir,
            files_written=written,
            stdout="",
            stderr="",
            exit_code=0,
        )


@pytest.fixture
def stub_ctx(tmp_path: Path) -> GenerationContext:
    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    return GenerationContext(
        psp_name="cashfree",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "out",
        target_module="lens.connectors.cashfree",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="2024-09-01",
        reports_dir=tmp_path / "_reports",
    )


def test_run_pipeline_post_processes_marker(stub_ctx: GenerationContext) -> None:
    runner = _StubRunner(files_to_create=[("connector.py", "x = 1\n")])
    asyncio.run(run_pipeline(ctx=stub_ctx, runner=runner, hooks=PipelineHooks(run_gates=False)))
    out = (stub_ctx.output_dir / "connector.py").read_text()
    assert out.startswith("# ─")
    assert "x = 1" in out


def test_run_pipeline_skips_existing_marker(stub_ctx: GenerationContext) -> None:
    marker = (
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree 2024-09-01\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
    )
    runner = _StubRunner(files_to_create=[("connector.py", marker + "\nx = 1\n")])
    asyncio.run(run_pipeline(ctx=stub_ctx, runner=runner, hooks=PipelineHooks(run_gates=False)))
    out = (stub_ctx.output_dir / "connector.py").read_text()
    assert out.count("DO NOT EDIT — autogenerated by Grace.") == 1


# --- tests_dir relocation -----------------------------------------------------


def test_relocated_tests_path_returns_none_when_unset(stub_ctx: GenerationContext) -> None:
    assert relocated_tests_path(stub_ctx) is None


def test_relocated_tests_path_composes_psp(stub_ctx: GenerationContext, tmp_path: Path) -> None:
    ctx = replace(stub_ctx, tests_dir=tmp_path / "tests" / "connectors")
    expected = tmp_path / "tests" / "connectors" / "cashfree"
    assert relocated_tests_path(ctx) == expected


def test_relocate_tests_noop_when_tests_dir_unset(
    stub_ctx: GenerationContext, tmp_path: Path
) -> None:
    """Tests stay inside the package when tests_dir is unset (legacy behavior)."""
    stub_ctx.output_dir.mkdir(parents=True, exist_ok=True)
    (stub_ctx.output_dir / "tests").mkdir()
    (stub_ctx.output_dir / "tests" / "test_x.py").write_text("def test_x(): pass\n")
    assert _relocate_tests(stub_ctx) is None
    assert (stub_ctx.output_dir / "tests" / "test_x.py").is_file()


def test_relocate_tests_noop_when_no_tests_subdir(
    stub_ctx: GenerationContext, tmp_path: Path
) -> None:
    """Relocation is a no-op when Claude didn't write a tests subdir."""
    stub_ctx.output_dir.mkdir(parents=True, exist_ok=True)
    ctx = replace(stub_ctx, tests_dir=tmp_path / "tests")
    assert _relocate_tests(ctx) is None


def test_relocate_tests_moves_tree_to_destination(
    stub_ctx: GenerationContext, tmp_path: Path
) -> None:
    stub_ctx.output_dir.mkdir(parents=True, exist_ok=True)
    src = stub_ctx.output_dir / "tests"
    src.mkdir()
    (src / "test_a.py").write_text("def test_a(): pass\n")
    (src / "conftest.py").write_text("import pytest\n")

    dest_root = tmp_path / "tests" / "connectors"
    ctx = replace(stub_ctx, tests_dir=dest_root)
    relocated = _relocate_tests(ctx)

    assert relocated == dest_root / "cashfree"
    assert not src.exists()
    assert (dest_root / "cashfree" / "test_a.py").is_file()
    assert (dest_root / "cashfree" / "conftest.py").is_file()


def test_relocate_tests_overwrites_existing_destination(
    stub_ctx: GenerationContext, tmp_path: Path
) -> None:
    """Regenerate must replace, not append. Stale files at the destination
    get cleared so the relocated tree is exactly what Claude produced."""
    stub_ctx.output_dir.mkdir(parents=True, exist_ok=True)
    src = stub_ctx.output_dir / "tests"
    src.mkdir()
    (src / "test_new.py").write_text("def test_new(): pass\n")

    dest_root = tmp_path / "tests" / "connectors"
    dest_psp = dest_root / "cashfree"
    dest_psp.mkdir(parents=True)
    (dest_psp / "test_stale.py").write_text("def test_stale(): pass\n")

    ctx = replace(stub_ctx, tests_dir=dest_root)
    _relocate_tests(ctx)

    assert (dest_psp / "test_new.py").is_file()
    assert not (dest_psp / "test_stale.py").exists()


def test_run_pipeline_relocates_tests_after_marker_post_processing(
    stub_ctx: GenerationContext, tmp_path: Path
) -> None:
    """The order matters: marker post-processing rglobs `*.py` under
    output_dir, so it must run BEFORE relocation. Verify by reading
    a relocated test file: it should carry the marker block."""
    dest_root = tmp_path / "tests_root" / "connectors"
    ctx = replace(stub_ctx, tests_dir=dest_root)
    runner = _StubRunner(
        files_to_create=[
            ("connector.py", "x = 1\n"),
            ("tests/test_create_order.py", "def test_x(): pass\n"),
        ]
    )
    asyncio.run(run_pipeline(ctx=ctx, runner=runner, hooks=PipelineHooks(run_gates=False)))

    # Connector stayed put with marker prepended.
    connector = (ctx.output_dir / "connector.py").read_text()
    assert connector.startswith("# ─")
    # Test file moved AND carries the marker (marker runs before relocation).
    moved = dest_root / "cashfree" / "test_create_order.py"
    assert moved.is_file()
    assert moved.read_text().startswith("# ─")
    # In-package tests dir is gone.
    assert not (ctx.output_dir / "tests").exists()
