from __future__ import annotations

from pathlib import Path

from grace.pipeline.gates import MypyReport, PytestReport
from grace.pipeline.types import GenerationContext, PspDocs
from grace.quality_rubric import (
    _parse_mypy_findings,
    _parse_pytest_findings,
    score_rubric,
)

FX = Path(__file__).parent / "fixtures" / "connectors"


def _ctx(tmp_path: Path) -> GenerationContext:
    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    return GenerationContext(
        psp_name="demo",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "pkg",
        target_module="lens.connectors.demo",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="x",
        reports_dir=tmp_path / "_reports",
    )


def _write_marker(p: Path, psp: str = "demo") -> None:
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        f"#  Source: {psp} x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        f"#  Regenerate: grace generate {psp} --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
    )


def _scaffold_full_pkg(out: Path) -> None:
    """Scaffold a domain-modular 0.2.0 connector package.

    Layout mirrors §3.2: root connector.py/webhooks.py/__init__.py; core/
    base.py + auth.py + status.py + models.py; orders/ and subscriptions/
    each with connector.py / status_map.py / webhooks.py.  All files carry
    the §4 marker.
    """
    # --- root files ---
    out.mkdir(parents=True, exist_ok=True)

    init_py = out / "__init__.py"
    _write_marker(init_py)
    init_py.write_text(
        init_py.read_text()
        + 'requires_lens = "^0.2"\n'
        + "from .connector import DemoConnector\n"
        + "from .webhooks import build_webhook_handlers\n"
        + "from lens.factory import ConnectorFactory\n"
        + 'ConnectorFactory.register("demo", DemoConnector)\n'
        + 'ConnectorFactory.register_webhook("demo", build_webhook_handlers)\n'
    )

    connector_py = out / "connector.py"
    _write_marker(connector_py)
    connector_py.write_text(
        connector_py.read_text()
        + "from lens.common import ConnectorError, ConnectorErrorReason\n"
        + "from .orders.connector import DemoOrders\n"
        + "from .subscriptions.connector import DemoSubscriptions\n"
        + "class DemoConnector(DemoOrders, DemoSubscriptions):\n"
        + "    # Error: WEBHOOK_SIGNATURE_FAILED raised by WebhookHandlers.verify\n"
        + "    pass\n"
    )

    webhooks_py = out / "webhooks.py"
    _write_marker(webhooks_py)
    webhooks_py.write_text(
        webhooks_py.read_text()
        + "def build_webhook_handlers(config: object) -> object: ...\n"
    )

    # Root auth.py: satisfies the T13-era pii_discipline scorer which looks at
    # `output_dir/auth.py`. T14 will update _score_pii_discipline to look at
    # core/auth.py instead.
    auth_py = out / "auth.py"
    _write_marker(auth_py)
    auth_py.write_text(
        auth_py.read_text()
        + "from lens.common import Maskable\n"
        + "# See core/auth.py for actual implementation.\n"
    )

    # --- core/ ---
    core_dir = out / "core"
    core_dir.mkdir()
    for name, content in [
        ("__init__.py", ""),
        (
            "base.py",
            "from lens.connector import Connector\n"
            "class _DemoBase(Connector):\n"
            "    def __init__(self, config: object) -> None: ...\n"
            "    @property\n"
            "    def name(self) -> str: return 'demo'\n"
            "    @property\n"
            "    def base_url(self) -> str: return 'https://api.example.com'\n"
            "    async def close(self) -> None: ...\n",
        ),
        ("auth.py", "from lens.common import Maskable\ndef sign(s: Maskable[str]) -> str: ...\n"),
        ("status.py", ""),
        ("models.py", ""),
    ]:
        f = core_dir / name
        _write_marker(f)
        f.write_text(f.read_text() + content)

    # --- orders/ ---
    orders_dir = out / "orders"
    orders_dir.mkdir()
    for name, content in [
        ("__init__.py", ""),
        (
            "connector.py",
            "from lens.payments_connector import PaymentsConnector\n"
            "from ..core.base import _DemoBase\n"
            "class DemoOrders(_DemoBase, PaymentsConnector):\n"
            "    @property\n"
            "    def supported_methods(self): return set()\n"
            "    @property\n"
            "    def supports_idempotency_key(self): return True\n"
            "    async def create_order(self, r): ...\n"
            "    async def sync_payment(self, r): ...\n"
            "    async def refund(self, r): ...\n"
            "    async def sync_refund(self, r): ...\n",
        ),
        ("status_map.py", "from lens.enums import PaymentAttemptStatus\nSTATUS_MAP = {}\n"),
        ("webhooks.py", ""),
    ]:
        f = orders_dir / name
        _write_marker(f)
        f.write_text(f.read_text() + content)

    # --- subscriptions/ ---
    subs_dir = out / "subscriptions"
    subs_dir.mkdir()
    for name, content in [
        ("__init__.py", ""),
        (
            "connector.py",
            "from lens.mandate_connector import MandateConnector\n"
            "from ..core.base import _DemoBase\n"
            "class DemoSubscriptions(_DemoBase, MandateConnector):\n"
            "    @property\n"
            "    def supported_mandate_rails(self): return set()\n"
            "    @property\n"
            "    def supports_pause(self): return False\n"
            "    @property\n"
            "    def supported_intervals(self): return set()\n"
            "    @property\n"
            "    def max_mandate_amount(self): return 0\n"
            "    async def create_subscription(self, r): ...\n"
            "    async def sync_subscription(self, r): ...\n"
            "    async def cancel_subscription(self, r): ...\n"
            "    async def pause_subscription(self, r): ...\n"
            "    async def resume_subscription(self, r): ...\n",
        ),
        ("status_map.py", ""),
        ("webhooks.py", ""),
    ]:
        f = subs_dir / name
        _write_marker(f)
        f.write_text(f.read_text() + content)


def test_rubric_full_score_when_everything_is_clean(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    assert report.total == 100, report.to_json()
    assert all(d.score == d.max for d in report.dimensions)


def test_rubric_marker_dimension_fails_when_marker_missing(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    # break one file's marker — the scorer finds the file but sees no §4 header
    (ctx.output_dir / "core" / "auth.py").write_text("def x(): ...\n")
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    marker_dim = next(d for d in report.dimensions if d.name == "marker_conformance")
    assert marker_dim.score == 0


def test_rubric_public_surface_full_score_via_fixture(tmp_path: Path) -> None:
    """The compliant fixture passes the domain-modular public-surface check
    with no deductions. Score must equal max (20)."""
    ctx = _ctx(tmp_path)
    report = score_rubric(
        ctx=ctx,
        output_dir=FX / "compliant",
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score == surface_dim.max, surface_dim.detail


def test_rubric_public_surface_orders_only_not_penalized(tmp_path: Path) -> None:
    """A payments-only PSP (no subscriptions/ dir) must not be docked for absent
    mandate methods — absent domains are not penalized (Cross-Cutting C1)."""
    ctx = _ctx(tmp_path)
    report = score_rubric(
        ctx=ctx,
        output_dir=FX / "orders_only",
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score == surface_dim.max, surface_dim.detail


def test_rubric_public_surface_docks_missing_register(tmp_path: Path) -> None:
    """When __init__.py omits ConnectorFactory.register the scorer docks points."""
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    # Overwrite __init__ to remove the register call.
    init_py = ctx.output_dir / "__init__.py"
    init_py.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: demo x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate demo --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
        "requires_lens = 'demo'\n"
        "x = 1\n"
    )
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score < surface_dim.max


def test_rubric_public_surface_docks_missing_domain_method(tmp_path: Path) -> None:
    """When subscriptions/connector.py omits a required lifecycle method the
    scorer docks points and mentions the missing method name in detail."""
    ctx = _ctx(tmp_path)
    report = score_rubric(
        ctx=ctx,
        output_dir=FX / "missing_mandate_method",
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score < surface_dim.max
    assert "cancel_subscription" in surface_dim.detail


def test_parse_mypy_findings_splits_per_line_and_drops_summary() -> None:
    stdout = (
        "lens/connectors/cashfree/connector.py:66: error: Argument \"secret_key\" ...\n"
        "lens/connectors/cashfree/connector.py:67: error: Argument \"webhook_secret\" ...\n"
        "lens/connectors/cashfree/connector.py:294: note: \"WebhookEvent\" defined in ...\n"
        "\n"
        "Found 3 errors in 1 file (checked 11 source files)\n"
    )
    findings = _parse_mypy_findings(stdout)
    assert len(findings) == 3
    assert findings[0].endswith('error: Argument "secret_key" ...')
    assert findings[2].endswith('"WebhookEvent" defined in ...')
    assert all(not f.startswith("Found ") for f in findings)


def test_parse_pytest_findings_captures_failures_and_short_summary() -> None:
    stdout = (
        "============================= test session starts =====\n"
        "collected 5 items\n"
        "tests/test_create_order.py F                          [ 20%]\n"
        "FAILED tests/test_create_order.py::test_happy - AssertionError: x\n"
        "ERROR tests/test_refund.py - lens.common.ConnectorError: ...\n"
        "=========================== short test summary info ===\n"
        "FAILED tests/test_create_order.py::test_happy - AssertionError: x\n"
        "ERROR tests/test_refund.py - lens.common.ConnectorError: ...\n"
        "=========================== 1 failed, 1 error in 0.3s\n"
    )
    findings = _parse_pytest_findings(stdout)
    # The short-summary lines (deterministic, one per failing case) are kept.
    failed = [f for f in findings if f.startswith("FAILED")]
    errored = [f for f in findings if f.startswith("ERROR")]
    assert len(failed) >= 1
    assert len(errored) >= 1


def test_rubric_type_correctness_carries_findings(tmp_path: Path) -> None:
    """The detail is a short summary; findings is the full per-error list."""
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(
            passed=False,
            stdout=(
                "x/y.py:10: error: foo\n"
                "x/y.py:11: error: bar\n"
                "x/y.py:12: note: see definition\n"
                "Found 2 errors in 1 file (checked 1 source file)\n"
            ),
            stderr="",
        ),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    type_dim = next(d for d in report.dimensions if d.name == "type_correctness")
    assert type_dim.score == 0
    assert type_dim.detail == "mypy failed: 2 error(s), 1 note(s)"
    assert type_dim.findings == [
        "x/y.py:10: error: foo",
        "x/y.py:11: error: bar",
        "x/y.py:12: note: see definition",
    ]
    # JSON round-trip preserves findings.
    import json as _json
    decoded = _json.loads(report.to_json())
    type_entry = next(d for d in decoded["dimensions"] if d["name"] == "type_correctness")
    assert type_entry["findings"] == type_dim.findings


def test_rubric_passes_with_55_when_mypy_and_coverage_fail(tmp_path: Path) -> None:
    """Even when mypy (−20) and coverage (partial −N) fail, the minimum floor
    from marker + surface + error + pii must be at least 35 (marker 5 + error
    handling 20 + pii 10 = 35 baseline if surface is 0; but surface passes a
    well-formed scaffold so total is higher).  Check the scaffold yields full
    surface so the floor is 55: marker 5 + surface 20 + error 20 + pii 10."""
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=False, stdout="", stderr=""),   # −20
        pytest_report=PytestReport(passed=True, coverage_pct=50.0, stdout="", stderr=""),  # partial
    )
    assert report.total < 100
    # Surface + marker + error-handling + pii dimensions still pass for a
    # well-formed scaffold: 20 + 5 + 20 + 10 = 55.
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score == surface_dim.max, surface_dim.detail
    assert report.total >= 55
