from __future__ import annotations

from pathlib import Path

from grace.pipeline.gates import MypyReport, PytestReport
from grace.pipeline.types import GenerationContext, PspDocs
from grace.quality_rubric import score_rubric


def _ctx(tmp_path: Path) -> GenerationContext:
    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    return GenerationContext(
        psp_name="demo",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "pkg",
        target_module="lens.connectors.demo",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="x",
    )


def _write_marker(p: Path, psp: str = "demo") -> None:
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        f"#  Source: {psp} x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        f"#  Regenerate: grace generate {psp} --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
    )


def _scaffold_full_pkg(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for name in ["__init__.py", "connector.py", "auth.py", "models.py", "status_map.py"]:
        f = out / name
        _write_marker(f)
        if name == "connector.py":
            f.write_text(
                f.read_text()
                + "from lens.connector import Connector\n"
                + "from lens.common import ConnectorError, ConnectorErrorReason\n"
                + "import httpx\n"
                + "class Demo(Connector):\n"
                + "    @property\n"
                + "    def name(self): return 'demo'\n"
                + "    @property\n"
                + "    def base_url(self): return 'https://api.example.com'\n"
                + "    @property\n"
                + "    def supported_methods(self): return set()\n"
                + "    @property\n"
                + "    def supports_idempotency_key(self): return True\n"
                + "    async def create_order(self, request): ...\n"
                + "    async def sync_payment(self, request): ...\n"
                + "    async def refund(self, request): ...\n"
                + "    async def sync_refund(self, request): ...\n"
                + "    async def handle_webhook(self, raw_payload, headers):\n"
                + "        try:\n"
                + "            ...\n"
                + "        except httpx.HTTPStatusError:\n"
                + "            raise ConnectorError(reason=ConnectorErrorReason.WEBHOOK_SIGNATURE_FAILED)\n"
                + "    async def close(self): ...\n"
            )
        elif name == "__init__.py":
            f.write_text(
                f.read_text()
                + 'requires_lens = "^0.1"\n'
                + "from .connector import Demo\n"
                + "from lens.factory import ConnectorFactory\n"
                + 'ConnectorFactory.register("demo", Demo)\n'
            )
        elif name == "auth.py":
            f.write_text(
                f.read_text()
                + "from lens.common import Maskable\n"
                + "def sign(secret: Maskable[str], payload: bytes) -> str: ...\n"
            )
        elif name == "status_map.py":
            f.write_text(
                f.read_text()
                + "from lens.enums import PaymentAttemptStatus, PaymentFailureCode\n"
                + "STATUS_MAP = {}\n"
            )
    tests = out / "tests"
    tests.mkdir()
    for t in [
        "test_create_order.py",
        "test_sync_payment.py",
        "test_refund.py",
        "test_sync_refund.py",
        "test_webhook.py",
    ]:
        f = tests / t
        _write_marker(f)


def test_rubric_full_score_when_everything_is_clean(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    assert report.total == 100, report.to_json()
    assert all(d.score == d.max for d in report.dimensions)


def test_rubric_marker_dimension_fails_when_marker_missing(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    # break one file's marker
    (ctx.output_dir / "auth.py").write_text("def x(): ...\n")
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    marker_dim = next(d for d in report.dimensions if d.name == "marker_conformance")
    assert marker_dim.score == 0


def test_rubric_public_surface_fails_when_class_missing(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    (ctx.output_dir / "connector.py").write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: demo x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate demo --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
        "x = 1\n"
    )
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score < surface_dim.max


def test_rubric_public_surface_fails_when_properties_missing(tmp_path: Path) -> None:
    """Missing @property declarations are caught at gate time, not deferred to
    a pytest-collection blowup."""
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    # Strip the @property declarations out — class becomes abstract.
    (ctx.output_dir / "connector.py").write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: demo x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate demo --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
        "from lens.connector import Connector\n"
        "from lens.common import ConnectorError, ConnectorErrorReason\n"
        "import httpx\n"
        "class Demo(Connector):\n"
        "    async def create_order(self, request): ...\n"
        "    async def sync_payment(self, request): ...\n"
        "    async def refund(self, request): ...\n"
        "    async def sync_refund(self, request): ...\n"
        "    async def handle_webhook(self, raw_payload, headers):\n"
        "        raise ConnectorError(reason=ConnectorErrorReason.WEBHOOK_SIGNATURE_FAILED)\n"
        "    async def close(self): ...\n"
    )
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=True, stdout="", stderr=""),
        pytest_report=PytestReport(passed=True, coverage_pct=95.0, stdout="", stderr=""),
    )
    surface_dim = next(d for d in report.dimensions if d.name == "public_surface")
    assert surface_dim.score < surface_dim.max
    assert "missing @property" in surface_dim.detail


def test_rubric_passes_with_55_when_mypy_and_coverage_fail(tmp_path: Path) -> None:
    ctx = _ctx(tmp_path)
    _scaffold_full_pkg(ctx.output_dir)
    report = score_rubric(
        ctx=ctx,
        output_dir=ctx.output_dir,
        mypy_report=MypyReport(passed=False, stdout="", stderr=""),    # -20
        pytest_report=PytestReport(passed=True, coverage_pct=50.0, stdout="", stderr=""),  # -25
    )
    assert report.total < 100
    assert report.total >= 55  # marker 5 + surface 20 + error 20 + pii 10 = 55 worst case
