from __future__ import annotations

from pathlib import Path

from grace.pipeline.marker import ensure_marker, has_marker, render_marker


def test_render_marker_seven_lines() -> None:
    text = render_marker(
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="https://docs.cashfree.com/openapi.yaml",
    )
    lines = text.strip("\n").splitlines()
    assert len(lines) == 7
    assert lines[1] == "#  DO NOT EDIT — autogenerated by Grace."


def test_has_marker_recognizes_well_formed(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree v1\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
        "\n"
        "x = 1\n"
    )
    assert has_marker(p) is True


def test_has_marker_rejects_missing(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    assert has_marker(p) is False


def test_ensure_marker_prepends_when_absent(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    text = p.read_text()
    assert text.startswith("# ─")
    assert "x = 1" in text


def test_ensure_marker_idempotent(tmp_path: Path) -> None:
    p = tmp_path / "x.py"
    p.write_text("x = 1\n")
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    once = p.read_text()
    ensure_marker(
        p,
        psp_name="cashfree",
        source_version="v1",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="x",
    )
    twice = p.read_text()
    assert once == twice
