from __future__ import annotations

from pathlib import Path

import pytest

from grace.docs_build import (
    build_docs,
    discover_connectors,
    introspect_connector,
    render_connector_md,
    render_llms_txt,
)
from grace.errors import GraceError, GraceErrorReason


# --- fixtures: a fake lens checkout with one well-formed connector ----------


def _write_marker(p: Path) -> None:
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: demo x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate demo --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
    )


def _make_connector(root: Path, *, psp: str, class_name: str) -> Path:
    pkg = root / "lens" / "connectors" / psp
    pkg.mkdir(parents=True)

    init_py = pkg / "__init__.py"
    _write_marker(init_py)
    init_py.write_text(
        init_py.read_text()
        + 'requires_lens = "^0.1"\n'
        + f"from .connector import {class_name}\n"
        + "from lens.factory import ConnectorFactory\n"
        + f'ConnectorFactory.register("{psp}", {class_name})\n'
    )

    connector_py = pkg / "connector.py"
    _write_marker(connector_py)
    connector_py.write_text(
        connector_py.read_text()
        + "from lens.connector import Connector\n"
        + "from lens.enums import PaymentMethod\n"
        + "\n"
        + f"class {class_name}(Connector):\n"
        + "    @property\n"
        + f'    def name(self) -> str: return "{psp}"\n'
        + "    @property\n"
        + f'    def base_url(self) -> str: return "https://api.example.com/{psp}"\n'
        + "    @property\n"
        + "    def supported_methods(self) -> set:\n"
        + "        return {PaymentMethod.CARD, PaymentMethod.UPI}\n"
        + "    @property\n"
        + "    def supports_idempotency_key(self) -> bool: return True\n"
        + "    async def create_order(self, request): ...\n"
        + "    async def sync_payment(self, request): ...\n"
        + "    async def refund(self, request): ...\n"
        + "    async def sync_refund(self, request): ...\n"
        + "    async def handle_webhook(self, raw_payload, headers): ...\n"
        + "    async def close(self): ...\n"
    )

    sm = pkg / "status_map.py"
    _write_marker(sm)
    sm.write_text(
        sm.read_text()
        + "from lens.enums import PaymentAttemptStatus, PaymentFailureCode\n"
        + "STATUS_MAP = {\n"
        + '    "SUCCESS": (PaymentAttemptStatus.SUCCESS, None),\n'
        + '    "FAILED":  (PaymentAttemptStatus.FAILED,  PaymentFailureCode.CARD_DECLINED),\n'
        + '    "USER_DROPPED": (PaymentAttemptStatus.FAILED, PaymentFailureCode.USER_DROPPED),\n'
        + "}\n"
    )

    for stub in ("auth.py", "models.py"):
        f = pkg / stub
        _write_marker(f)

    return pkg


# --- tests ------------------------------------------------------------------


def test_discover_finds_connector_dirs(tmp_path: Path) -> None:
    _make_connector(tmp_path, psp="demo", class_name="Demo")
    _make_connector(tmp_path, psp="other", class_name="Other")
    # Add a directory that shouldn't be picked up (no connector.py).
    (tmp_path / "lens" / "connectors" / "_legacy").mkdir(parents=True)
    pkgs = discover_connectors(tmp_path)
    names = sorted(p.name for p in pkgs)
    assert names == ["demo", "other"]


def test_discover_empty(tmp_path: Path) -> None:
    assert discover_connectors(tmp_path) == []


def test_introspect_extracts_locked_surface(tmp_path: Path) -> None:
    pkg = _make_connector(tmp_path, psp="demo", class_name="Demo")
    s = introspect_connector(pkg)
    assert s.psp_name == "demo"
    assert s.class_name == "Demo"
    # handle_webhook is no longer in LOCKED_FLOWS (webhook handling lives in
    # the webhook layer, not the capability interface).
    assert sorted(s.flows) == sorted(
        ["create_order", "sync_payment", "refund", "sync_refund"]
    )
    assert "handle_webhook" not in s.flows
    assert sorted(s.supported_methods) == ["CARD", "UPI"]
    assert s.base_url == "https://api.example.com/demo"
    assert sorted(s.psp_status_terms) == ["FAILED", "SUCCESS", "USER_DROPPED"]
    assert s.requires_lens == "^0.1"
    assert s.self_registers is True


def test_introspect_misnamed_class(tmp_path: Path) -> None:
    """Class name doesn't match the rubric's expected PascalCase — still introspectable."""
    pkg = _make_connector(tmp_path, psp="demo", class_name="DemoConnector")
    s = introspect_connector(pkg)
    assert s.class_name == "DemoConnector"
    assert s.psp_name == "demo"


def test_render_llms_txt_lists_each_connector(tmp_path: Path) -> None:
    _make_connector(tmp_path, psp="demo", class_name="Demo")
    _make_connector(tmp_path, psp="other", class_name="Other")
    pkgs = discover_connectors(tmp_path)
    summaries = [introspect_connector(p) for p in pkgs]
    out = render_llms_txt(summaries)
    assert "Connectors: 2" in out
    assert "## Demo" in out
    assert "connector_id: demo" in out
    assert "## Other" in out
    assert "payment_methods: CARD, UPI" in out
    # Flow order matches LOCKED_FLOWS (handle_webhook dropped in T16).
    assert "flows: create_order, sync_payment, refund, sync_refund" in out
    # handle_webhook must NOT appear in any connector's flows: line.
    for line in out.splitlines():
        if line.startswith("flows:"):
            assert "handle_webhook" not in line, f"handle_webhook in flows line: {line}"


def test_render_connector_md_includes_quickfacts(tmp_path: Path) -> None:
    pkg = _make_connector(tmp_path, psp="demo", class_name="Demo")
    s = introspect_connector(pkg)
    md = render_connector_md(s)
    assert md.startswith("# Demo\n")
    assert 'Registry key: `"demo"`' in md
    assert "Requires Lens: `^0.1`" in md
    assert "- `CARD`" in md
    assert "- `UPI`" in md
    assert "ConnectorFactory.create(config)" in md


def test_build_docs_writes_outputs(tmp_path: Path) -> None:
    _make_connector(tmp_path, psp="demo", class_name="Demo")
    _make_connector(tmp_path, psp="other", class_name="Other")
    result = build_docs(lens_root=tmp_path)

    out_root = tmp_path / "docs-generated"
    assert out_root.is_dir()
    assert (out_root / "llms.txt").is_file()
    assert (out_root / "connectors" / "demo.md").is_file()
    assert (out_root / "connectors" / "other.md").is_file()
    assert len(result.files_written) == 3  # llms.txt + 2 connector mds
    assert len(result.connectors) == 2


def test_build_docs_raises_when_no_connectors(tmp_path: Path) -> None:
    with pytest.raises(GraceError) as exc:
        build_docs(lens_root=tmp_path)
    assert exc.value.reason is GraceErrorReason.CONTEXT_BUNDLE_INVALID
