from __future__ import annotations

from pathlib import Path

import jinja2


def _env() -> jinja2.Environment:
    return jinja2.Environment(
        loader=jinja2.FileSystemLoader(
            Path(__file__).parent.parent / "src" / "grace" / "templates"
        ),
        keep_trailing_newline=True,
        autoescape=False,
    )


def test_marker_format_matches_constitution_section_4() -> None:
    rendered = _env().get_template("marker.j2").render(
        psp_name="cashfree",
        source_version="2024-09-01",
        generated_utc_iso8601="2026-05-20T12:00:00Z",
        grace_version="0.1.0",
        source_uri="https://docs.cashfree.com/openapi.yaml",
    )
    lines = rendered.strip("\n").splitlines()
    assert len(lines) == 7, lines
    assert lines[0].startswith("# ─") and lines[6].startswith("# ─")
    assert lines[1] == "#  DO NOT EDIT — autogenerated by Grace."
    assert lines[2] == "#  Source: cashfree 2024-09-01"
    assert lines[3] == "#  Generated: 2026-05-20T12:00:00Z"
    assert lines[4] == "#  Generator: grace 0.1.0"
    assert (
        lines[5]
        == "#  Regenerate: grace generate cashfree --from https://docs.cashfree.com/openapi.yaml"
    )
