"""Tests for marker de-churn: body-idempotent marker restoration.

Scenarios covered:
  (a) File whose body is unchanged vs HEAD → restored to HEAD bytes (marker not re-stamped).
  (b) File whose body changed vs HEAD → keeps the new marker / body.
  (c) New file (not in HEAD) → keeps its fresh marker.
  (d) File in a directory that is not inside any git repo → skipped safely (no crash).
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from grace.pipeline.marker import dechurn_if_unchanged, extract_body, ensure_marker


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_MARKER_BLOCK = (
    "# ──────────────────────────────────────────────────────────────────────\n"
    "#  DO NOT EDIT — autogenerated by Grace.\n"
    "#  Source: cashfree v1\n"
    "#  Generated: 2026-01-01T00:00:00Z\n"
    "#  Generator: grace 0.1.0\n"
    "#  Regenerate: grace generate cashfree --from x\n"
    "# ──────────────────────────────────────────────────────────────────────\n"
)

_BODY = "\nx = 1\n"


def _init_git_repo(path: Path) -> None:
    """Initialise a bare git repo at *path* with a single commit."""
    path.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init"], cwd=path, capture_output=True, check=True)
    subprocess.run(
        ["git", "config", "user.email", "test@example.com"],
        cwd=path,
        capture_output=True,
        check=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "Test"],
        cwd=path,
        capture_output=True,
        check=True,
    )


def _commit_file(repo: Path, rel: str, content: str) -> None:
    """Write *content* to *repo/rel*, stage it, and create a commit."""
    target = repo / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    subprocess.run(["git", "add", rel], cwd=repo, capture_output=True, check=True)
    subprocess.run(
        ["git", "commit", "-m", "initial"],
        cwd=repo,
        capture_output=True,
        check=True,
    )


# ---------------------------------------------------------------------------
# extract_body unit tests
# ---------------------------------------------------------------------------


def test_extract_body_strips_marker_block() -> None:
    text = _MARKER_BLOCK + _BODY
    assert extract_body(text) == _BODY


def test_extract_body_returns_full_text_when_no_marker() -> None:
    text = "x = 1\n"
    assert extract_body(text) == text


def test_extract_body_handles_file_shorter_than_seven_lines() -> None:
    text = "# short\n"
    assert extract_body(text) == text


# ---------------------------------------------------------------------------
# dechurn_if_unchanged — scenario (a): body unchanged → restored to HEAD
# ---------------------------------------------------------------------------


def test_dechurn_restores_head_when_body_unchanged(tmp_path: Path) -> None:
    """When the body didn't change, the file must revert to HEAD's exact content."""
    repo = tmp_path / "repo"
    head_content = _MARKER_BLOCK + _BODY

    _init_git_repo(repo)
    _commit_file(repo, "connector.py", head_content)

    # Simulate a regen that only restamped the marker (different timestamp/version).
    new_marker = (
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree v1\n"
        "#  Generated: 2026-06-06T12:00:00Z\n"  # newer timestamp
        "#  Generator: grace 0.9.1\n"            # newer version
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
    )
    target = repo / "connector.py"
    target.write_text(new_marker + _BODY)

    dechurn_if_unchanged(target, repo)

    # File must be byte-identical to HEAD.
    assert target.read_text() == head_content


# ---------------------------------------------------------------------------
# dechurn_if_unchanged — scenario (b): body changed → keeps new content
# ---------------------------------------------------------------------------


def test_dechurn_keeps_new_content_when_body_changed(tmp_path: Path) -> None:
    """When the body changed, the freshly-stamped file must be left as-is."""
    repo = tmp_path / "repo"
    head_content = _MARKER_BLOCK + _BODY

    _init_git_repo(repo)
    _commit_file(repo, "connector.py", head_content)

    new_marker = (
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree v1\n"
        "#  Generated: 2026-06-06T12:00:00Z\n"
        "#  Generator: grace 0.9.1\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
    )
    changed_body = "\nx = 2\n"  # body is different
    new_content = new_marker + changed_body

    target = repo / "connector.py"
    target.write_text(new_content)

    dechurn_if_unchanged(target, repo)

    # File must be left as the newly-stamped version (not reverted).
    assert target.read_text() == new_content


# ---------------------------------------------------------------------------
# dechurn_if_unchanged — scenario (c): new file (not in HEAD) → keeps marker
# ---------------------------------------------------------------------------


def test_dechurn_keeps_new_file_marker(tmp_path: Path) -> None:
    """A brand-new file that doesn't exist in HEAD keeps its fresh marker."""
    repo = tmp_path / "repo"
    _init_git_repo(repo)

    # Commit an unrelated file so HEAD exists.
    _commit_file(repo, "other.py", "y = 0\n")

    new_marker = (
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: cashfree v1\n"
        "#  Generated: 2026-06-06T12:00:00Z\n"
        "#  Generator: grace 0.9.1\n"
        "#  Regenerate: grace generate cashfree --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n"
    )
    new_content = new_marker + _BODY

    target = repo / "brand_new.py"
    target.write_text(new_content)

    dechurn_if_unchanged(target, repo)

    # File must be left with the fresh marker (it wasn't in HEAD).
    assert target.read_text() == new_content


# ---------------------------------------------------------------------------
# dechurn_if_unchanged — scenario (d): non-git directory → skipped safely
# ---------------------------------------------------------------------------


def test_dechurn_skips_when_not_in_git_repo(tmp_path: Path) -> None:
    """When the file is not inside a git repo, dechurn must not crash."""
    # tmp_path itself is NOT a git repo (and the test conftest chdirs to an
    # isolated cwd, so there's no accidental repo ancestor).
    non_git_dir = tmp_path / "not_a_repo"
    non_git_dir.mkdir()
    target = non_git_dir / "connector.py"
    original_content = _MARKER_BLOCK + _BODY
    target.write_text(original_content)

    # Supplying a fake git_root that doesn't contain the file to simulate a
    # "no repo found" path — but we exercise _git_root_for via the orchestrate
    # helper; here we test dechurn_if_unchanged directly with a non-existent root.
    fake_root = tmp_path / "fake_root"
    fake_root.mkdir()

    # Must not raise even when git show fails.
    dechurn_if_unchanged(target, fake_root)

    # Content unchanged (de-churn skipped gracefully).
    assert target.read_text() == original_content
