from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import jinja2

_TEMPLATE_DIR = Path(__file__).parent.parent / "templates"
_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(_TEMPLATE_DIR),
    keep_trailing_newline=True,
    autoescape=False,
)


def render_marker(
    *,
    psp_name: str,
    source_version: str,
    generated_utc_iso8601: str | None = None,
    grace_version: str,
    source_uri: str,
) -> str:
    ts = generated_utc_iso8601 or datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return _env.get_template("marker.j2").render(
        psp_name=psp_name,
        source_version=source_version,
        generated_utc_iso8601=ts,
        grace_version=grace_version,
        source_uri=source_uri,
    )


def has_marker(path: Path) -> bool:
    """Return True iff the first non-empty content of `path` is a well-formed marker block."""
    lines = path.read_text().splitlines()
    if len(lines) < 7:
        return False
    if not lines[0].startswith("# ─"):
        return False
    if lines[1].strip() != "#  DO NOT EDIT — autogenerated by Grace.":
        return False
    for i, prefix in enumerate(
        ("#  Source:", "#  Generated:", "#  Generator:", "#  Regenerate:"), start=2
    ):
        if not lines[i].startswith(prefix):
            return False
    if not lines[6].startswith("# ─"):
        return False
    return True


def ensure_marker(
    path: Path,
    *,
    psp_name: str,
    source_version: str,
    generated_utc_iso8601: str | None = None,
    grace_version: str,
    source_uri: str,
) -> None:
    if has_marker(path):
        return
    marker = render_marker(
        psp_name=psp_name,
        source_version=source_version,
        generated_utc_iso8601=generated_utc_iso8601,
        grace_version=grace_version,
        source_uri=source_uri,
    )
    body = path.read_text()
    sep = "" if marker.endswith("\n") else "\n"
    path.write_text(marker + sep + body)
