from __future__ import annotations

from grace.pipeline.types import GenerationContext


PROMPT_TEMPLATE = """\
You are generating a Python PSP connector for the Orbit Lens.

Target package layout (you will create these files in the current working directory):

  __init__.py
  connector.py
  auth.py
  models.py
  status_map.py
  tests/__init__.py
  tests/test_create_order.py
  tests/test_sync_payment.py
  tests/test_refund.py
  tests/test_sync_refund.py
  tests/test_webhook.py

╔══════════════════════════════════════════════════════════════════════╗
║ LOCKED SURFACE — DO NOT DEVIATE                                       ║
╚══════════════════════════════════════════════════════════════════════╝

These are the most common ways a generation can go wrong. Read them BEFORE
reading the rulebook, then re-check against this list before you finish.

1. CLASS NAME is the PSP name in PascalCase, with **no `Connector` suffix**.
   ✓ `class Cashfree(Connector):`        — for PSP `cashfree`
   ✗ `class CashfreeConnector(Connector):`
   ✗ `class CashfreeClient(Connector):`

2. IMPORTS come from these exact module paths:
     from lens.connector import Connector
     from lens.factory import ConnectorFactory, ConnectorConfig
     from lens.domain_types import (
         CreateOrderRequest, CreateOrderResponse,
         SyncPaymentRequest, SyncPaymentResponse,
         RefundRequest, RefundResponse,
         SyncRefundRequest, SyncRefundResponse,
         PaymentAttempt, RefundEvent, WebhookEvent,
         Amount,
     )
     from lens.enums import (
         Currency, PaymentMethod,
         OrderStatus, PaymentAttemptStatus, RefundStatus,
         PaymentFailureCode, WebhookEventType, ConnectorErrorReason,
     )
     from lens.common import Maskable, ConnectorError
   ✗ Do NOT import from `lens.connector_abc`, `lens.types`, `lens.models`, etc.
   ✗ Do NOT import a `Money` type — the locked money type is `Amount`.

3. EVERY FLOW METHOD IS `async def`. Use `httpx.AsyncClient`. Ground rule 3.
   ✓ `async def create_order(self, request: CreateOrderRequest) -> CreateOrderResponse:`
   ✗ `def create_order(self, request): ...`

4. DOMAIN TYPES use the **exact** field names from `domain_types.md`:
   - `request.amount.minor_units: int`            (NOT `.value`, NOT `.amount`)
   - `request.amount.currency: Currency`
   - `request.customer_id: str | None`            (NOT `request.customer.id`, NOT a nested object)
   - `request.idempotency_key: str | None`
   ✗ No `float()` conversions anywhere on the domain surface (ground rule 10).

5. `__init__.py` MUST do two things at module scope:
     requires_lens = "{lens_version_constraint}"
     from .connector import <Psp>
     from lens.factory import ConnectorFactory
     ConnectorFactory.register("<psp>", <Psp>)
   ✗ Don't just `__all__ = [...]` and call it done.

6. CREDENTIALS in `auth.py` are typed `Maskable[str]`, not bare `str`.
     api_key: Maskable[str]
     secret_key: Maskable[str]
   Read with `.expose()` only inside the HTTP call (never log the result).
   ✗ Do NOT define a `<Psp>Config` dataclass. The config type is `lens.factory.ConnectorConfig`.

7. WEBHOOK SIGNATURE FAILURE raises a typed error, not `ValueError`:
     raise ConnectorError(reason=ConnectorErrorReason.WEBHOOK_SIGNATURE_FAILED)
   ✗ `raise ValueError("bad signature")` will score 0 on error_handling.

8. STATUS ENUMS are LOCKED — you may NOT add new values:
   - PaymentAttemptStatus = PENDING | SUCCESS | FAILED                  (three values, no more)
   - RefundStatus         = PENDING | SUCCESS | FAILED
   - OrderStatus          = CREATED | PAID | PARTIALLY_REFUNDED | REFUNDED | EXPIRED | FAILED
   ✗ NO `CAPTURED`, `AUTHORIZED`, `CANCELLED`, `VOID`, `REJECTED`, etc.
     If the PSP has those terms, map them via status_map.py into PENDING/SUCCESS/FAILED
     + a PaymentFailureCode.

9. FAILURE CODES come from this exact list (PaymentFailureCode enum):
   USER_DROPPED, USER_CANCELLED, CARD_DECLINED, INSUFFICIENT_FUNDS,
   AUTHENTICATION_FAILED, FRAUD_BLOCKED, FRAUD_REVIEW_PENDING,
   INVALID_INSTRUMENT, PSP_ERROR, NETWORK_ERROR, UNKNOWN.
   ✗ NO `PAYMENT_DECLINED`, `CUSTOMER_CANCELLED`, `EXPIRED_CARD`, `TIMEOUT`, etc.

10. MARKER BLOCK at the very top of each .py file is **the only** doc-header.
    Grace writes the marker for you if you forget; do NOT also write your own
    `# Code generated by ... DO NOT EDIT` comment — that ends up duplicated.

11. HTTP CLIENT lifecycle:
    - Build `httpx.AsyncClient(...)` in `__init__`. Owned by the Connector.
    - Close it in `async def close(self) -> None: await self._client.aclose()`.
    - Tests inject a mock via `httpx.MockTransport`.

╔══════════════════════════════════════════════════════════════════════╗
║ POST-GENERATION SELF-CHECK                                            ║
╚══════════════════════════════════════════════════════════════════════╝

Before you exit, grep your own output for these and verify each one matches:

  $ grep -E "^class [A-Z][a-z]+\\(Connector\\)" connector.py     # exactly one match
  $ grep "from lens.connector import Connector" connector.py      # present
  $ grep "ConnectorFactory.register" __init__.py                   # present
  $ grep "requires_lens" __init__.py                               # present
  $ grep "async def" connector.py                                  # six matches (5 flows + close)
  $ grep "Maskable" auth.py                                        # at least once
  $ grep "WEBHOOK_SIGNATURE_FAILED" connector.py                   # at least once
  $ grep -E "Money|float\\(" connector.py models.py                # ZERO matches

╔══════════════════════════════════════════════════════════════════════╗
║ CONTEXT FILES                                                         ║
╚══════════════════════════════════════════════════════════════════════╝

Read these in order — `ground_rules.md` first, then the type contracts, then
the per-flow patterns. Re-read `connector_abc.md` whenever in doubt about a
method signature.

{rulebook_block}

╔══════════════════════════════════════════════════════════════════════╗
║ PSP DOCUMENTATION                                                     ║
╚══════════════════════════════════════════════════════════════════════╝

{source_block}

╔══════════════════════════════════════════════════════════════════════╗
║ THIS RUN                                                              ║
╚══════════════════════════════════════════════════════════════════════╝

Target module: {target_module}
Generator version: grace {grace_version}
Source version: {source_version}
Lens version constraint: {lens_version_constraint}

Generate the package. Do not ask follow-up questions. Write the files, run
the post-generation self-check above against your own output, then exit.
"""


def build_prompt(ctx: GenerationContext) -> str:
    rulebook_block = "\n".join(f"  - {p}" for p in ctx.rulebook_paths)
    if ctx.psp_docs.source_kind == "url":
        source_block = (
            f"  - URL: {ctx.psp_docs.source_uri}\n"
            f"  - Content fetched at generation time "
            f"(use the Read tool on the cached file: see CWD)."
        )
    else:
        source_block = "\n".join(f"  - {p}" for p in ctx.psp_docs.local_paths)
    return PROMPT_TEMPLATE.format(
        rulebook_block=rulebook_block,
        source_block=source_block,
        target_module=ctx.target_module,
        grace_version=ctx.grace_version,
        source_version=ctx.source_version,
        lens_version_constraint=ctx.lens_version_constraint,
    )
