from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path

import pytest

from grace.errors import GraceError, GraceErrorReason
from grace.pipeline import PipelineHooks, run_pipeline
from grace.pipeline.types import GenerationContext, GenerationResult, PspDocs


pytestmark = pytest.mark.integration


@dataclass
class _StubRunner:
    files: list[tuple[str, str]]

    async def is_available(self) -> tuple[bool, str]:
        return (True, "ok")

    async def generate(self, ctx: GenerationContext) -> GenerationResult:
        written: list[Path] = []
        for name, body in self.files:
            p = ctx.output_dir / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)
            written.append(p)
        return GenerationResult(
            output_dir=ctx.output_dir,
            files_written=written,
            stdout="",
            stderr="",
            exit_code=0,
        )


def _write_marker(p: Path) -> None:
    p.write_text(
        "# ──────────────────────────────────────────────────────────────────────\n"
        "#  DO NOT EDIT — autogenerated by Grace.\n"
        "#  Source: demo x\n"
        "#  Generated: 2026-05-20T12:00:00Z\n"
        "#  Generator: grace 0.1.0\n"
        "#  Regenerate: grace generate demo --from x\n"
        "# ──────────────────────────────────────────────────────────────────────\n\n"
    )


def test_quality_report_json_exposes_each_gate_decision(tmp_path: Path) -> None:
    """When rubric ≥ 60 but coverage < 80%, the report's top-level `passed`
    is False (drift fix), and each gate's individual decision is visible."""
    from grace.pipeline.gates import run_gates_blocking, MypyReport, PytestReport
    from unittest.mock import patch
    import json

    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    ctx = GenerationContext(
        psp_name="demo",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "out",
        target_module="lens.connectors.demo",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="x",
        reports_dir=tmp_path / "_reports",
    )
    # Scaffold a complete package so the rubric scores high.
    out = ctx.output_dir
    out.mkdir(parents=True, exist_ok=True)
    for fname in ["__init__.py", "connector.py", "auth.py", "models.py", "status_map.py"]:
        f = out / fname
        _write_marker(f)
        if fname == "connector.py":
            f.write_text(
                f.read_text()
                + "from lens.connector import Connector\n"
                + "from lens.common import ConnectorError, ConnectorErrorReason\n"
                + "import httpx\n"
                + "class Demo(Connector):\n"
                + "    @property\n    def name(self) -> str: return 'demo'\n"
                + "    @property\n    def base_url(self) -> str: return 'x'\n"
                + "    @property\n    def supported_methods(self): return set()\n"
                + "    @property\n    def supports_idempotency_key(self) -> bool: return True\n"
                + "    async def create_order(self, request): ...\n"
                + "    async def sync_payment(self, request): ...\n"
                + "    async def refund(self, request): ...\n"
                + "    async def sync_refund(self, request): ...\n"
                + "    async def handle_webhook(self, raw_payload, headers):\n"
                + "        raise ConnectorError(reason=ConnectorErrorReason.WEBHOOK_SIGNATURE_FAILED)\n"
                + "    async def close(self): ...\n"
            )
        elif fname == "__init__.py":
            f.write_text(
                f.read_text()
                + 'requires_lens = "^0.1"\n'
                + "from .connector import Demo\n"
                + "from lens.factory import ConnectorFactory\n"
                + 'ConnectorFactory.register("demo", Demo)\n'
            )
        elif fname == "auth.py":
            f.write_text(f.read_text() + "from lens.common import Maskable\n")
        elif fname == "status_map.py":
            f.write_text(f.read_text() + "from lens.enums import PaymentAttemptStatus\n")
    (out / "tests").mkdir()
    for t in (
        "test_create_order.py",
        "test_sync_payment.py",
        "test_refund.py",
        "test_sync_refund.py",
        "test_webhook.py",
    ):
        _write_marker(out / "tests" / t)

    # Force the gate path: mypy clean, coverage 55% (below the 80% gate),
    # rubric should still hit ≥60 because the package is structurally sound.
    fake_result = GenerationResult(
        output_dir=out, files_written=[], stdout="", stderr="", exit_code=0
    )
    with (
        patch("grace.pipeline.gates.run_mypy", return_value=MypyReport(passed=True, stdout="", stderr="")),
        patch(
            "grace.pipeline.gates.run_pytest_with_cov",
            return_value=PytestReport(passed=True, coverage_pct=55.0, stdout="", stderr=""),
        ),
    ):
        with pytest.raises(GraceError) as exc:
            run_gates_blocking(ctx=ctx, result=fake_result)
    assert exc.value.reason is GraceErrorReason.QUALITY_GATE_FAILED
    assert "coverage: 55.0%" in (exc.value.detail or "")

    report = json.loads((ctx.reports_dir / "quality_report.json").read_text())
    # Top-level passed reflects all gates — the drift fix.
    assert report["passed"] is False
    # Each gate visible separately.
    assert report["gates"]["mypy"]["passed"] is True
    assert report["gates"]["tests"]["passed"] is False
    assert "55.0% coverage" in report["gates"]["tests"]["actual"]
    assert "all tests pass" in report["gates"]["tests"]["threshold"]
    assert report["gates"]["rubric"]["passed"] is True
    assert isinstance(report["gates"]["rubric"]["actual"], int)
    assert report["gates"]["rubric"]["actual"] >= 60
    # Per-dimension rubric breakdown still present.
    assert "rubric" in report
    assert "dimensions" in report["rubric"]


def test_pipeline_raises_when_rubric_fails(tmp_path: Path) -> None:
    rb = tmp_path / "rb.md"
    rb.write_text("rb")
    ctx = GenerationContext(
        psp_name="demo",
        rulebook_paths=[rb],
        psp_docs=PspDocs(source_uri="x", source_kind="local_file", local_paths=[rb]),
        output_dir=tmp_path / "out",
        target_module="lens.connectors.demo",
        lens_version_constraint="^0.1",
        grace_version="0.1.0",
        source_version="x",
        reports_dir=tmp_path / "_reports",
    )
    runner = _StubRunner(files=[
        ("orders/connector.py", "class DemoOrders:\n    pass\n"),
    ])
    with pytest.raises(GraceError) as exc:
        asyncio.run(run_pipeline(ctx=ctx, runner=runner, hooks=PipelineHooks(run_gates=True)))
    assert exc.value.reason is GraceErrorReason.QUALITY_GATE_FAILED
